stages:
  make_dataset:
    cmd: python ./src/data/make_dataset.py /data/raw/final_features.csv   
    deps:
    - ./data/raw/final_features.csv
    - ./src/data/make_dataset.py
    params:
    - make_dataset.test_split
    - make_dataset.seed
    outs:
    - ./data/processed/
    
  build_features:
    cmd: python ./src/features/build_features.py /data/processed
    deps:
    - ./data/processed 
    - ./src/features/build_features.py
    outs:
    - ./data/interim

  train_model:
    cmd: python ./src/models/train_model.py /data/interim
    deps:
    - ./data/interim
    - ./src/models/train_model.py
    params:
    - train_model.params_grid_pipe
    - train_model.cv
    outs:
    - ./models/
  # visualize:
  #   cmd: python .\src\visualization\visualize.py .\models\model.joblib .\data\processed\
  #   deps:
  #   - .\data\processed\
  #   - .\models\model.joblib
  #   - .\src\visualization\visualize.py
  #   outs:
  #   - dvclive

# metrics:
# - dvclive/metrics.json