make_dataset:
  test_split: 0.3
  seed: 22

build_features:
  sampling_strategy: 'minority'

train_model:
  params_grid: {'C': [1,10,50],
               'kernel': ['poly','linear','rbf','precomputer'],
             }
  cv: 5

  params_grid_pipe: {'svm__C': [10],
               'svm__kernel': ['poly','linear','rbf'],
             }